services:
  directus:
    image: directus/directus:latest
    container_name: line21-directus
    ports:
      - "8055:8055"
    environment:
      KEY: 'your-secret-key-here'
      SECRET: 'your-secret-here'
      DB_CLIENT: 'pg'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      ADMIN_EMAIL: 'admin@line21.dk'
      ADMIN_PASSWORD: 'admin123'
      CACHE_ENABLED: 'false'
      CACHE_STORE: 'memory'
      RATE_LIMITER_ENABLED: 'false'
      TELEMETRY: 'false'
      LOG_LEVEL: 'info'
      PUBLIC_URL: 'http://localhost:8055'
      AUTH_PROVIDERS: ''
      AUTH_DISABLE_DEFAULT: 'false'
      EXTENSIONS_AUTO_RELOAD: 'true'
      EXTENSIONS_PATH: '/directus/extensions'
    volumes:
      - ./extensions:/directus/extensions
      - ./uploads:/directus/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: line21-postgres
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 