version: "1"

services:
  - type: web
    name: line21-directus
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: KEY
        value: "line21-directus-secret-key-2024"
      - key: SECRET
        value: "line21-directus-secret-2024-super-secure"
      - key: DB_CLIENT
        value: "pg"
      - key: DB_HOST
        value: "dpg-cp8j8v6n7f5s73f8v8q0-a.oregon-postgres.render.com"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "directus"
      - key: DB_USER
        value: "directus"
      - key: DB_PASSWORD
        value: "tZNc7UGQ8jz6Gkm3uAlVu8LPhcRnbdaY"
      - key: ADMIN_EMAIL
        value: "admin@line21.dk"
      - key: ADMIN_PASSWORD
        value: "admin123"
      - key: DB_SSL
        value: "true"
      - key: CORS_ENABLED
        value: "true"
      - key: CORS_ORIGIN
        value: "*"
      - key: CORS_METHODS
        value: "GET,POST,PATCH,DELETE,OPTIONS"
      - key: CORS_ALLOWED_HEADERS
        value: "Content-Type,Authorization"
      - key: CORS_EXPOSED_HEADERS
        value: "Content-Range"
      - key: CORS_CREDENTIALS
        value: "true"
      - key: CORS_MAX_AGE
        value: "18000"
      - key: PUBLIC_URL
        value: "https://line21-directus.onrender.com"
      - key: TELEMETRY
        value: "false"
      - key: CACHE_ENABLED
        value: "false"
      - key: RATE_LIMITER_ENABLED
        value: "false"
      - key: LOG_LEVEL
        value: "debug"
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"

# Database er allerede oprettet som: dpg-cp8j8v6n7f5s73f8v8q0-a.oregon-postgres.render.com 