services:
  - type: web
    name: line21-strapi-cms
    env: node
    plan: free
    buildCommand: echo "Build complete"
    startCommand: node -e "const http = require('http'); const port = process.env.PORT || 10000; const server = http.createServer((req, res) => { res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify({message: 'Line21 CMS Server Running!', port: port, timestamp: new Date().toISOString()})); }); server.listen(port, '0.0.0.0', () => console.log('✅ Server running on port', port));"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 