services:
  - type: web
    name: line21-cms
    env: node
    plan: free
    buildCommand: NODE_OPTIONS='--max-old-space-size=512' npm run build
    startCommand: NODE_OPTIONS='--max-old-space-size=512' npm run start:simple
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: PUBLIC_URL
        value: https://line21-cms.onrender.com
      - key: GITHUB_TOKEN
        value: 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 